version: 0.2

env:
  variables:
    STAGE: production

phases:
  install:
    runtime-version:
      nodejs: 20
    commands:
      - npm install -g serverless
      - npm install

  # pre_build:
  #   commands:
  #     - npm run test
  build:
    commands:
      - npm run build
      - serverless deploy