service: MovieBrowserAPI

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-2
  memorySize: 128
  timeout: 30
  stage: prd

functions:
  MovieBrowserAPI:
    handler: index.postHandler
    events:
      - http:
          path: /
          method: get
          cors: true
          private: false
